---
kind: pipeline
type: docker
name: build

steps:

  - name: docker
    image: plugins/docker
    when:
      branch:
        - master
    settings:
      dockerfile: Dockerfile
      repo: openflag/docker-openflag-builder
      tags:
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
